### ISSUE TITLE
Logobar results in a warning on every slide

### ISSUE THREAD

**Issue by jnothman** [malramsay64/usyd-beamer-theme#8]
I'm getting the following for every slide. If you have any quick ideas for fixes, they would be very welcome

```
 (./slides.vrb) <use USYDLogo-eps-converted-to.pdf>
Overfull \vbox (20.49776pt too high) has occurred while \output is active
```

**Comment by malramsay64** [comment]
I think that might be because the logo is taller than the box it is in. Logo is 3em, box is 2.7 em. This is a size I didn't change in the modifications during #6. Should be able to change the height of the logo in the innertheme.

**Comment by jnothman** [comment]
I can't see where to change it. It's no big deal; rendering fine.

**Comment by jnothman** [comment]
(Changing the logo height to 2.7em doesn't remove the warning, either.)

**Comment by malramsay64** [comment]
#9 Should fix the warnings, at least it does for the example slides.

**Comment by jnothman** [comment]
thank you. sorry for my silence

**Comment by malramsay64** [comment]
No worries
